## Optimized Breakfast Mix

Import required packages

In [1]:
import numpy as np
from numpy import linalg

""" Solve the nutritional programming problem here using the variable x
    for your solution                                                   """

''' initial data set with np.array added before b'''
A = np.array([[105,130,120],[1,3,5],[2,4,2]])
b = np.array([[245],[6],[7]])
'''use np.linalg.solve from NumPy documentation to solve'''
x = np.linalg.solve(A, b)
print(x)
'''Print data'''
print('Optimized Breakfast Mix (% by weight): Cheerios:',x[0,0]/sum(x),', Cap’n Crunch:',x[1,0]/sum(x),',  Lucky Charms:',x[2,0]/sum(x),'.')
'''Test resultant'''
y = A.dot(x)-b

[[0.11940299]
 [1.57462687]
 [0.23134328]]
Optimized Breakfast Mix (% by weight): Cheerios: [0.0620155] , Cap’n Crunch: [0.81782946] ,  Lucky Charms: [0.12015504] .


Solve the nutritional programming problem here using the variable x for your solution

In [2]:
A = np.array([[105,130,120],[1,3,5],[2,4,2]])
b = np.array([[245],[6],[7]])

In [3]:
x = np.linalg.solve(A, b)
print(x)

[[0.11940299]
 [1.57462687]
 [0.23134328]]


Print Solution

In [4]:
print('Optimized Breakfast Mix (% by weight): Cheerios:',x[0,0]/sum(x),', Cap’n Crunch:',x[1,0]/sum(x),',  Lucky Charms:',x[2,0]/sum(x),'.')

Optimized Breakfast Mix (% by weight): Cheerios: [0.0620155] , Cap’n Crunch: [0.81782946] ,  Lucky Charms: [0.12015504] .


Test resultant

In [5]:
y = A.dot(x)-b
print(y)

[[0.0000000e+00]
 [0.0000000e+00]
 [8.8817842e-16]]
